# This is a basic workflow to help you get started with Actions

name: github pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod


    # Runs hugo shell
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.10
      with:
        hugo-version: '0.70.0'
        extended: true
    
    - name: Build
      run: hugo --minify
    
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.7
      with:
        github_token: ${{ secrets.hugo_ielts_yayin_token }}
        publish_dir: ./public
